dist: bionic
language: cpp

cache:
  ccache: true
  directories:
    - $HOME/.mx

before_install:
  - |
    if [ "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ]; then
      echo "Building a tag."
    else
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        echo "Building a pull request."
        TRAVIS_COMMIT_RANGE="$TRAVIS_BRANCH"
      fi
      if [ -z "$TRAVIS_COMMIT_RANGE" ]; then
        echo "Building a new branch."
        TRAVIS_COMMIT_RANGE="HEAD~..HEAD"
      fi
      (git diff --name-only $TRAVIS_COMMIT_RANGE || echo "") | grep -qvE '(\.md$)' || {
        echo "Only docs were updated, stopping build process."
        exit
      }
    fi
  - wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/jvmci-19.3-b03/openjdk-8u222-jvmci-19.3-b03-linux-amd64.tar.gz
  - mkdir openjdk1.8.0-jvmci
  - tar --strip 1 -C openjdk1.8.0-jvmci -xvf openjdk-*.tar.gz
  - git clone https://github.com/graalvm/mx.git

before_script:
  - export JAVA_HOME=$TRAVIS_BUILD_DIR/openjdk1.8.0-jvmci
  - export PATH=$TRAVIS_BUILD_DIR/mx:$JAVA_HOME/bin:$PATH

script:
  - mx sforceimports
  - mx sversions
  - mx checkstyle --primary
  - mx build
    #  - cd ../graal/vm
    #  - mx --dy nodeprof,/compiler --force-bash-launchers=true --disable-polyglot build
    #  - cd -
  - mx test-all
  - mx --dy /compiler build
  - mx --dy /compiler test-npm

deploy:
  provider: releases
  api_key:
    secure: "ZgAJNRliSHrtT0AOv/zpzhy24DoYPAuuR8/17gpO4YgbucVrB7N6MUbLywNiI8yvnGil2xZjcFUaw/mEaz0mO4k4Il2RtEC1vOZGRU9C17kGroaMUlWsdLaNNU2dIDpsHMzFaGTerCnENzuzSo27Op2/LiNJrG++3VFT9Ab9XPq3pGBCiuzwmwDOm73uNovsskRlkVEtj1H0Xp7kfkxXXfEFZFRZl+0Pltg2l+++hj/Ay6RvHvS/QfaAMb6BAjZWQHV9DA7QV0Ezmukwoe7YlKlgOdI5aKq3fx/bBbp3fyCxnQuMjV9CzomT5lenhxhlcawBfdQXkVY+maQsc5JFnEXXFjA88ju2eIkP3TxjMJCsZipT/19QpWHhCjzcNpzjfCF6G9kDB3qMuy0FyDXtyvuHdk3HCAKzY/bfWqPzuspix99E2qHJVONdmS3lv6TgVYEbN+GhsLhqBnGl/typon3YfBZXnv8A6ntkhhiPnr0gwu/sStYR3wFFp8BqaYCpms0p2iVwwbjpKK0dsah/YZ/4WoCbbvEGSq1sx7sbjYnD8kjKBbK3ne121FAQH+ChXeNLpIrsPX9FVjezWCd1bpU4fFEjUYBkTb+P/d3fNOdj/UPGDVgRrNpUUrkY3SvIxPJ/oMGpgdEoGOGzMrvSBt3ObaEKgtaRCtWxMKdNZF8="
  file: build/nodeprof.jar
  skip_cleanup: true
  on:
    tags: true

