name: NodeProf Test Action

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up mx
      run: |
        git clone --depth 1 https://github.com/graalvm/mx.git
        echo `pwd`/mx >> $GITHUB_PATH
    - name: fetch imports
      run: mx sforceimports
    - name: log versions
      run: mx sversions
    - name: set up jdk
      run: |
        mx fetch-jdk --java-distribution openjdk8 --config ../graal/common.json --to $GITHUB_WORKSPACE --alias openjdk1.8.0-jvmci
        echo "JAVA_HOME=$GITHUB_WORKSPACE/openjdk1.8.0-jvmci" >> GITHUB_ENV
    #- name: style checks
    #  run: |
    #    mx checkstyle --primary
    #    mx checkcopyrights-nodeprof
    - name: build
      run: mx build
    - name: test
      run: |
        mx npm-deps
        mx test-all

